import type { Metadata } from "next";
import { Inter,Parisienne,Dancing_Script, } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"],weight: ["400"],variable: '--font-Inter' });
const parisienne = Parisienne({ subsets: ["latin"], weight: ["400"], variable: '--font-Parisienne' });
const dancing_script = Dancing_Script({ subsets: ["latin"], weight: ["400"], variable: '--font-DancingScript' });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={[inter.variable, parisienne.variable,dancing_script.variable].join(' ')}>{children}</body>
    </html>
  );
}
